[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
optimizer = true
optimizer_runs = 10
via_ir = true
solc_version = '0.8.30'
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./script/" }]

[profile.default.fmt]
sort_import = true
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "preserve"
override_spacing = true
ignore = []

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable", "asm-keccak256", "screaming-snake-case-immutable"]

[profile.test]
gas_reports = ["*"]

[profile.coverage]
via_ir = true
no_match_coverage = "(script|test)"

[dependencies]
forge-std = "1.10.0"
"@openzeppelin-contracts" = "5.4.0"
"@openzeppelin-contracts-upgradeable" = "5.4.0"
bls-solidity = { version = "0.3.0", url = "https://github.com/randa-mu/bls-solidity/archive/refs/tags/v0.3.0.zip" }
uniswap-permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
uniswap-permit2-unlocked = "1.0.0"
solmate = "89365b880c4f3c786bdd453d4b8e8fe410344a69"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
